# Generated by Django 4.1.1 on 2022-09-23 02:52

import base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, unique=True, validators=[base.validators.validateNome])),
                ('email', models.CharField(max_length=100, null=True, unique=True, validators=[base.validators.validateEmail])),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[base.validators.validateCpf])),
                ('rg', models.CharField(blank=True, max_length=7, null=True, unique=True, validators=[base.validators.validateRg])),
                ('endereco', models.CharField(blank=True, max_length=100, null=True, unique=True, validators=[base.validators.validateEndereco])),
                ('data_nascimento', models.DateField()),
                ('data_entrada', models.DateField()),
                ('turno', models.CharField(blank=True, choices=[('1', 'Manhã'), ('2', 'Tarde'), ('3', 'Manhã e Tarde')], max_length=10, null=True, unique=True)),
                ('departamento', models.CharField(blank=True, choices=[('1', 'Coodernação'), ('2', 'Professor'), ('3', 'Aluno')], max_length=20, null=True, unique=True)),
                ('senha', models.CharField(blank=True, max_length=8, null=True, unique=True, validators=[base.validators.validateSenha])),
            ],
        ),
    ]
