# Generated by Django 4.1.1 on 2022-09-28 17:08

import base.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=True, validators=[base.validators.validateNome, base.validators.validateNoDigits])),
                ('email', models.CharField(max_length=100, null=True, unique=True, validators=[base.validators.validateEmail])),
                ('contato', models.CharField(max_length=11, null=True, validators=[base.validators.validateContato])),
                ('cpf', models.CharField(max_length=11, null=True, unique=True, validators=[base.validators.validateCpf])),
                ('rg', models.CharField(max_length=7, null=True, unique=True, validators=[base.validators.validateRg])),
                ('endereco', models.CharField(max_length=100, null=True, validators=[base.validators.validateEndereco])),
                ('data_nascimento', models.DateField()),
                ('data_entrada', models.DateField()),
                ('foto', models.FileField(blank=True, upload_to='documents/%d/%m/%Y', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
                ('historico', models.FileField(blank=True, upload_to='documents/%d/%m/%Y', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('turno', models.CharField(blank=True, choices=[('1', 'Manhã'), ('2', 'Tarde'), ('3', 'Integral')], max_length=10, null=True)),
                ('departamento', models.CharField(blank=True, choices=[('1', 'Coodernação'), ('2', 'Professor'), ('3', 'Aluno')], default='', max_length=20, null=True)),
            ],
        ),
    ]
