# Generated by Django 4.1.1 on 2022-09-20 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('rg', models.CharField(max_length=7)),
                ('endereco', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('data_entrada', models.DateField()),
                ('turno', models.CharField(max_length=10)),
                ('senha', models.CharField(max_length=8)),
            ],
        ),
    ]
