# Generated by Django 4.1.1 on 2022-09-27 02:30

from django.db import migrations, models
import usuario.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, upload_to=usuario.models.usuario_file_name),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='historico',
            field=models.FileField(blank=True, upload_to=usuario.models.usuario_file_name),
        ),
    ]
