# Generated by Django 4.1.1 on 2022-09-28 17:33

import base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.FileField(blank=True, upload_to='documents/%d/%m/%Y', validators=[base.validators.validateFoto]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='historico',
            field=models.FileField(blank=True, upload_to='documents/%d/%m/%Y', validators=[base.validators.validateHistorico]),
        ),
    ]
