# Generated by Django 4.1.1 on 2022-09-23 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='departamento',
            field=models.CharField(blank=True, choices=[('1', 'Coodernação'), ('2', 'Professor'), ('3', 'Aluno')], default='', max_length=20, null=True, unique=True),
        ),
    ]
