# Generated by Django 4.1.1 on 2022-09-26 04:36

import base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuario_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='departamento',
            field=models.CharField(blank=True, choices=[('1', 'Coodernação'), ('2', 'Professor'), ('3', 'Aluno')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='endereco',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[base.validators.validateEndereco]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[base.validators.validateNome]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='turno',
            field=models.CharField(blank=True, choices=[('1', 'Manhã'), ('2', 'Tarde'), ('3', 'Manhã e Tarde')], max_length=10, null=True),
        ),
    ]
