# Generated by Django 4.1.1 on 2022-09-28 00:56

import base.validators
from django.db import migrations, models
import usuario.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuario_foto_alter_usuario_historico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contato',
            field=models.CharField(max_length=11, null=True, validators=[base.validators.validateContato]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, upload_to=usuario.models.usuario_file_name, validators=[base.validators.validateFoto]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='historico',
            field=models.FileField(blank=True, upload_to=usuario.models.usuario_file_name, validators=[base.validators.validateHistorico]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=100, null=True, validators=[base.validators.validateNome, base.validators.validateNoDigits]),
        ),
    ]
