# Generated by Django 4.1.1 on 2022-10-17 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_usuario_contato_alter_usuario_foto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password1', models.CharField(max_length=8)),
                ('password2', models.CharField(max_length=8)),
                ('username', models.ManyToManyField(to='usuario.usuario')),
            ],
        ),
    ]
