# Generated by Django 4.1.1 on 2022-10-17 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
