# Generated by Django 4.1.1 on 2022-10-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
